#!/usr/bin/env python3
"""Classify cppcheck MISRA findings by ISO 26262-6 ASIL-C category.

Reads a cppcheck XML report and the committed rule->category map, then enforces
the ASIL-C policy:

    * Mandatory violation  -> FAIL (never deviatable)
    * Required  violation  -> FAIL (deviation requires documented record)
    * Advisory  violation  -> WARN (reported, non-blocking)

Writes a Markdown summary and exits non-zero when any Mandatory/Required
violation remains after suppressions.
"""
import argparse
import csv
import os
import re
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict

RULE_RE = re.compile(r"misra[-_]c?2?0?1?2?[-_](\d+\.\d+)", re.IGNORECASE)
# cppcheck ids look like 'misra-c2012-15.5'. Directives are not emitted by the
# addon, but we keep the column for completeness.


def load_categories(path):
    cats = {}
    with open(path, newline="") as fh:
        for row in csv.reader(fh):
            if not row or row[0].startswith("#") or row[0] == "rule":
                continue
            cats[row[0].strip()] = row[1].strip()
    return cats


def rule_of(error_id):
    m = RULE_RE.search(error_id or "")
    return m.group(1) if m else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--xml", required=True)
    ap.add_argument("--categories", required=True)
    ap.add_argument("--summary", required=True)
    args = ap.parse_args()

    cats = load_categories(args.categories)

    findings = defaultdict(list)  # category -> [(rule, file, line, msg)]
    rule_counts = defaultdict(int)

    if os.path.exists(args.xml) and os.path.getsize(args.xml) > 0:
        try:
            tree = ET.parse(args.xml)
        except ET.ParseError:
            tree = None
        if tree is not None:
            for err in tree.getroot().iter("error"):
                eid = err.get("id", "")
                rule = rule_of(eid)
                if rule is None:
                    continue
                loc = err.find("location")
                f = loc.get("file") if loc is not None else "?"
                ln = loc.get("line") if loc is not None else "?"
                cat = cats.get(rule, "Unknown")
                findings[cat].append((rule, f, ln, err.get("msg", "")))
                rule_counts[rule] += 1

    mand = findings.get("Mandatory", [])
    req = findings.get("Required", [])
    adv = findings.get("Advisory", [])
    unk = findings.get("Unknown", [])

    lines = []
    lines.append("# MISRA C:2012 Compliance Summary (ASIL-C)\n")
    lines.append("_Generated by tools/misra/classify.py. Policy: zero "
                 "Mandatory/Required violations; Advisory reported only._\n")
    lines.append("")
    lines.append("| Category | Violations | Policy | Status |")
    lines.append("|:--|--:|:--|:--|")
    lines.append(f"| Mandatory | {len(mand)} | must be 0 | "
                 f"{'PASS' if not mand else 'FAIL'} |")
    lines.append(f"| Required | {len(req)} | must be 0 (or documented deviation) | "
                 f"{'PASS' if not req else 'FAIL'} |")
    lines.append(f"| Advisory | {len(adv)} | reported only | INFO |")
    if unk:
        lines.append(f"| Unknown | {len(unk)} | review rule mapping | WARN |")
    lines.append("")

    def dump(title, items):
        if not items:
            return
        lines.append(f"## {title} ({len(items)})\n")
        lines.append("| Rule | Location | Message |")
        lines.append("|:--|:--|:--|")
        for rule, f, ln, msg in sorted(items):
            short = os.path.relpath(f) if os.path.exists(f) else f
            safe = msg.replace("|", "\\|")
            lines.append(f"| {rule} | {short}:{ln} | {safe} |")
        lines.append("")

    dump("Mandatory violations", mand)
    dump("Required violations", req)
    dump("Unknown-category findings", unk)
    if adv:
        lines.append(f"## Advisory violations ({len(adv)})\n")
        lines.append("_Non-blocking. Track for cleanup._\n")
        by_rule = defaultdict(int)
        for rule, *_ in adv:
            by_rule[rule] += 1
        lines.append("| Rule | Count |")
        lines.append("|:--|--:|")
        for rule in sorted(by_rule):
            lines.append(f"| {rule} | {by_rule[rule]} |")
        lines.append("")

    with open(args.summary, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    blocking = len(mand) + len(req)
    print(f"MISRA: {len(mand)} Mandatory, {len(req)} Required, "
          f"{len(adv)} Advisory, {len(unk)} Unknown.")
    if blocking:
        print(f"ASIL-C GATE FAILED: {blocking} Mandatory/Required violation(s). "
              f"See {args.summary}.", file=sys.stderr)
        return 1
    print("ASIL-C MISRA gate PASSED (no Mandatory/Required violations).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
